name: Build and push the image

on:
  push:
    branches:
      - 'main'
      
env:
  IMAGE_REPOSITORY_NAME: brezyweather
  IMAGE_TAG: 1.0.0

jobs:
  build:
    name: Build BrezyWeather container image
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log into Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build & push the image
        uses: docker/build-push-action@v2
        with:
          push: true
          #tags example: cbbrezyweatherprodxxx.azurecr.io/brezyweather:1.0.0
          tags: ${{ secrets.SERVER }}/${{ env.IMAGE_REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}        
          
          
